2019-06-11 16:57:15.154 ERROR[http-nio-9999-exec-6]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:15.154 ERROR[http-nio-9999-exec-6]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:15.155 ERROR[http-nio-9999-exec-6]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:15.155 ERROR[http-nio-9999-exec-6]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:15.156 ERROR[http-nio-9999-exec-6]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:15.156 ERROR[http-nio-9999-exec-6]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:15.156 ERROR[http-nio-9999-exec-6]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:15.156 ERROR[http-nio-9999-exec-6]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:15.156 ERROR[http-nio-9999-exec-6]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:15.157 ERROR[http-nio-9999-exec-6]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:18.829 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:18.829 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:18.829 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:18.830 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:18.830 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:18.830 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:18.830 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:18.830 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:18.830 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 16:57:18.831 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:02:16.081 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:02:18.269 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:02:18.270 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:02:18.270 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:02:18.270 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:02:18.271 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:02:18.271 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:02:18.272 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:02:18.272 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:02:18.272 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:02:18.277 ERROR[pool-4-thread-1]o.s.scheduling.support.TaskUtils$LoggingErrorHandler.handleError:96 -Unexpected error occurred in scheduled task.
org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268)
	at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.convertLettuceAccessException(LettuceKeyCommands.java:817)
	at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.del(LettuceKeyCommands.java:131)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.del(DefaultedRedisConnection.java:69)
	at org.springframework.data.redis.core.RedisTemplate.lambda$delete$2(RedisTemplate.java:709)
	at org.springframework.data.redis.core.RedisTemplate$$Lambda$759/386053898.doInRedis(Unknown Source)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.delete(RedisTemplate.java:709)
	at org.springframework.session.data.redis.RedisSessionExpirationPolicy.cleanExpiredSessions(RedisSessionExpirationPolicy.java:133)
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.cleanupExpiredSessions(RedisOperationsSessionRepository.java:430)
	at org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration.lambda$configureTasks$0(RedisHttpSessionConfiguration.java:248)
	at org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration$$Lambda$720/59879483.run(Unknown Source)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy135.del(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.del(LettuceKeyCommands.java:129)
	... 20 common frames omitted
2019-06-11 17:31:23.635 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:31:23.635 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:31:23.636 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:31:23.636 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:31:23.636 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:31:23.636 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:31:23.636 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:31:23.637 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:31:23.637 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:31:23.637 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:34:42.114 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:35:17.610 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:36:51.708 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:36:51.710 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:36:51.711 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:36:51.711 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:36:51.711 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:36:51.711 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:36:51.711 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:36:51.712 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:37:43.745 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:37:43.745 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:37:43.746 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:37:43.746 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:37:43.747 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:37:43.747 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:37:43.747 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:37:43.748 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:37:43.748 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:37:43.748 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:38:16.904 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:38:26.604 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:39:42.346 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:39:42.347 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:39:42.347 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:39:42.348 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:39:42.348 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:39:42.348 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:39:42.349 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:39:42.349 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:41:24.511 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:31.852 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:31.852 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:31.852 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:31.853 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:31.853 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:31.853 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:37.271 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:37.271 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:37.271 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:37.271 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:37.272 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:37.272 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:37.272 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:37.272 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:42:37.272 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:45:32.071 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:45:32.071 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:45:32.072 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:45:32.072 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:45:32.072 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:45:32.072 ERROR[http-nio-9999-exec-1]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:26.047 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:26.048 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:26.048 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:26.048 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:26.048 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:26.048 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:26.049 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:26.049 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:26.049 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:44.913 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:44.914 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:44.914 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:44.914 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:44.914 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:44.914 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:44.914 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:44.915 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:46:44.915 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:47:22.338 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:47:22.341 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:47:22.342 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:47:22.342 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:47:22.342 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:47:22.343 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:47:22.343 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:47:22.344 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:47:22.344 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:48:02.704 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:48:02.704 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:48:02.705 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:48:02.705 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:48:02.705 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:48:02.706 ERROR[http-nio-9999-exec-3]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:48:57.431 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:48:57.431 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:48:57.432 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:48:57.432 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:48:57.432 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:48:57.432 ERROR[http-nio-9999-exec-2]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:49:14.845 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:49:14.846 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:49:14.846 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:49:14.846 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:49:14.846 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:49:14.847 ERROR[http-nio-9999-exec-4]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:50:15.149 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:51:42.496 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:51:42.496 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:51:42.497 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:51:42.497 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 17:51:42.497 ERROR[http-nio-9999-exec-5]com.cjw.springbootstarter.service.impl.ArcGpServiceImpl.resultForStatisticsWithLevel:271 -地类统计出现严重问题,请检查编码系统是否合理
2019-06-11 18:59:55.052 ERROR[main]org.springframework.boot.SpringApplication.reportFailure:858 -Application run failed
org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table 'gsdb.t_code_tdly2007' doesn't exist
### The error may exist in com/cjw/springbootstarter/mapper/onemap/CodeTdly2007Mapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,code,name,pid,level,type  FROM t_code_tdly2007
### Cause: java.sql.SQLSyntaxErrorException: Table 'gsdb.t_code_tdly2007' doesn't exist
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'gsdb.t_code_tdly2007' doesn't exist
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:234)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy67.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.executeForMany(PageMapperMethod.java:173)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.execute(PageMapperMethod.java:86)
	at com.baomidou.mybatisplus.core.override.PageMapperProxy.invoke(PageMapperProxy.java:64)
	at com.sun.proxy.$Proxy93.selectList(Unknown Source)
	at com.cjw.springbootstarter.base.ApplicationReady.refreshDbToData(ApplicationReady.java:92)
	at com.cjw.springbootstarter.base.ApplicationReady.onApplicationEvent(ApplicationReady.java:48)
	at com.cjw.springbootstarter.base.ApplicationReady.onApplicationEvent(ApplicationReady.java:40)
	at com.cjw.springbootstarter.base.ApplicationReady$$EnhancerBySpringCGLIB$$1c7fb3f4.onApplicationEvent(<generated>)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:105)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.cjw.springbootstarter.SpringbootStarterApplication.main(SpringbootStarterApplication.java:19)
Caused by: java.sql.SQLSyntaxErrorException: Table 'gsdb.t_code_tdly2007' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:974)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:391)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy143.query(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 21 common frames omitted
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-7]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xabbdbecc, L:/127.0.0.1:25464 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-16]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x02314608, L:/127.0.0.1:25467 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-10]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xb3241a32, L:/127.0.0.1:25469 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-14]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xc6d20ae9, L:/127.0.0.1:25459 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-13]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x689fba7e, L:/127.0.0.1:25455 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-9]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x092d0deb, L:/127.0.0.1:25468 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.139 ERROR[redisson-netty-4-14]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x00733493, L:/127.0.0.1:25476 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-3]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xeda3ed5d, L:/127.0.0.1:25486 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.140 ERROR[redisson-netty-4-16]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x4ecb5314, L:/127.0.0.1:25471 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.139 ERROR[redisson-netty-4-13]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xd387428f, L:/127.0.0.1:25474 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.139 ERROR[redisson-netty-4-7]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x35938069, L:/127.0.0.1:25480 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-5]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xc3f6209d, L:/127.0.0.1:25477 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-2]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x50201d43, L:/127.0.0.1:25483 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-8]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xdf8ad4e4, L:/127.0.0.1:25475 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-6]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xb035a90a, L:/127.0.0.1:25481 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-1]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x4d6585bb, L:/127.0.0.1:25485 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-4]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x633aeb96, L:/127.0.0.1:25472 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-12]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xb57c3fb5, L:/127.0.0.1:25482 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-15]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xd6447996, L:/127.0.0.1:25460 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.144 ERROR[redisson-netty-4-8]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xb0f14e07, L:/127.0.0.1:25463 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.144 ERROR[redisson-netty-4-2]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x54f26216, L:/127.0.0.1:25456 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.144 ERROR[redisson-netty-4-4]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xba3ff397, L:/127.0.0.1:25465 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.135 ERROR[redisson-netty-4-11]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x48080f86, L:/127.0.0.1:25457 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.139 ERROR[redisson-netty-4-9]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x08803efe, L:/127.0.0.1:25479 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.139 ERROR[redisson-netty-4-10]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x7e299503, L:/127.0.0.1:25473 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.142 ERROR[redisson-netty-4-3]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xa25e97cf, L:/127.0.0.1:25470 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.142 ERROR[redisson-netty-4-5]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x64ad3269, L:/127.0.0.1:25461 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.144 ERROR[redisson-netty-4-12]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xc51b2c06, L:/127.0.0.1:25458 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.144 ERROR[redisson-netty-4-1]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x0af7ea3e, L:/127.0.0.1:25466 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.144 ERROR[redisson-netty-4-6]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0xae072642, L:/127.0.0.1:25462 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.144 ERROR[redisson-netty-4-15]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x0bc4279e, L:/127.0.0.1:25478 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.148 ERROR[redisson-netty-4-3]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x46f5251d, L:/127.0.0.1:25487 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-06-11 18:59:55.148 ERROR[redisson-netty-4-11]org.redisson.client.handler.CommandsQueue.exceptionCaught:148 -Exception occured. Channel: [id: 0x9677d91c, L:/127.0.0.1:25484 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
